"""
MathTinyML Weight Exporter
将训练好的 PyTorch 模型权重通过 SVD 分解，导出为 C 头文件，
供 MathTinyML.hpp 在 MCU 上直接使用。

用法:
    python export_weights.py --model my_model.pt --rank 32 --output model_weights.h

如果你没有 PyTorch 模型，可以去掉 --model 参数，脚本会生成一个演示用的随机权重。
"""

import argparse
import numpy as np
import os


def svd_decompose(weight_matrix, rank):
    """
    对权重矩阵做 SVD 分解：W(m×n) ≈ A(m×r) × B(r×n)
    rank 越小，省的内存越多，但精度损失越大。
    """
    U, S, Vt = np.linalg.svd(weight_matrix, full_matrices=False)
    
    # 只保留前 rank 个奇异值
    U_r = U[:, :rank]
    S_r = np.diag(S[:rank])
    Vt_r = Vt[:rank, :]
    
    # A = U_r × Σ_r，B = Vt_r
    A = U_r @ S_r
    B = Vt_r
    
    return A.astype(np.float32), B.astype(np.float32)


def matrix_to_c_array(matrix, name):
    """把一个 numpy 矩阵转成 C 语言数组字符串"""
    rows, cols = matrix.shape
    lines = [f"// {name}: {rows}x{cols} ({rows * cols} floats, {rows * cols * 4} bytes)"]
    lines.append(f"const float {name}[{rows} * {cols}] = {{")
    
    for i in range(rows):
        row_vals = ", ".join(f"{matrix[i, j]:.8f}f" for j in range(cols))
        lines.append(f"    {row_vals},")
    
    lines.append("};")
    return "\n".join(lines)


def export_header(A, B, input_dim, output_dim, rank, output_path):
    """生成 .h 头文件"""
    header = f"""/**
 * MathTinyML Model Weights (Auto-generated by export_weights.py)
 * 
 * Architecture: {input_dim} -> {output_dim}  (Low-Rank: r={rank})
 * Memory saved: {100 - int(100 * rank * (input_dim + output_dim) / (input_dim * output_dim))}%
 *
 * A: {A.shape[0]}x{A.shape[1]}  B: {B.shape[0]}x{B.shape[1]}
 * Original: {input_dim * output_dim * 4} bytes -> Compressed: {(A.size + B.size) * 4} bytes
 */

#ifndef MATH_TINY_ML_WEIGHTS_H
#define MATH_TINY_ML_WEIGHTS_H

#include <stdint.h>

// Model dimensions
#define MTML_INPUT_DIM  {input_dim}
#define MTML_OUTPUT_DIM {output_dim}
#define MTML_RANK       {rank}

{matrix_to_c_array(A, "MTML_WEIGHT_A")}

{matrix_to_c_array(B, "MTML_WEIGHT_B")}

#endif // MATH_TINY_ML_WEIGHTS_H
"""
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(header)
    
    print(f"\n[+] 导出完成: {output_path}")
    print(f"    A: {A.shape[0]}x{A.shape[1]}  ({A.size * 4} bytes)")
    print(f"    B: {B.shape[0]}x{B.shape[1]}  ({B.size * 4} bytes)")
    print(f"    总大小: {(A.size + B.size) * 4} bytes")
    print(f"    原始大小: {input_dim * output_dim * 4} bytes")
    print(f"    节省: {100 - int(100 * (A.size + B.size) / (input_dim * output_dim))}%")


def main():
    parser = argparse.ArgumentParser(description="MathTinyML 权重导出工具")
    parser.add_argument("--model", type=str, default=None,
                        help="PyTorch 模型文件路径 (.pt)")
    parser.add_argument("--layer-name", type=str, default="fc1.weight",
                        help="要导出的层名称 (默认: fc1.weight)")
    parser.add_argument("--input-dim", type=int, default=768,
                        help="输入维度 (默认: 768)")
    parser.add_argument("--output-dim", type=int, default=768,
                        help="输出维度 (默认: 768)")
    parser.add_argument("--rank", type=int, default=32,
                        help="SVD 低秩近似 rank (默认: 32)")
    parser.add_argument("--output", type=str, default="model_weights.h",
                        help="输出的 C 头文件名 (默认: model_weights.h)")
    
    args = parser.parse_args()
    
    if args.model and os.path.exists(args.model):
        # 从 PyTorch 模型加载
        try:
            import torch
            model = torch.load(args.model, map_location="cpu", weights_only=False)
            
            # 尝试获取指定层的权重
            if hasattr(model, args.layer_name.replace(".weight", "")):
                layer = getattr(model, args.layer_name.replace(".weight", ""))
                weight = layer.weight.detach().numpy()
            elif isinstance(model, dict) and args.layer_name in model:
                weight = model[args.layer_name].detach().numpy()
            else:
                # 尝试直接当做 state_dict
                weight = model[args.layer_name].detach().numpy()
            
            print(f"[*] 从 {args.model} 加载层 '{args.layer_name}': {weight.shape}")
            input_dim, output_dim = weight.shape
            
        except ImportError:
            print("[!] 未安装 PyTorch，使用随机权重演示。")
            print("    安装 PyTorch: pip install torch")
            weight = np.random.randn(args.output_dim, args.input_dim).astype(np.float32) * 0.02
            input_dim, output_dim = args.input_dim, args.output_dim
        except Exception as e:
            print(f"[!] 加载模型失败: {e}")
            print("[*] 回退到随机权重演示...")
            weight = np.random.randn(args.output_dim, args.input_dim).astype(np.float32) * 0.02
            input_dim, output_dim = args.input_dim, args.output_dim
    else:
        # 演示模式：生成随机权重
        if args.model:
            print(f"[!] 找不到模型文件: {args.model}")
        print("[*] 演示模式：生成随机权重")
        print(f"    输入维度: {args.input_dim}, 输出维度: {args.output_dim}")
        weight = np.random.randn(args.output_dim, args.input_dim).astype(np.float32) * 0.02
        input_dim, output_dim = args.input_dim, args.output_dim
    
    # SVD 分解
    print(f"\n[*] SVD 分解中... rank={args.rank}")
    A, B = svd_decompose(weight, args.rank)
    
    # 计算重建误差
    reconstructed = A @ B
    error = np.linalg.norm(weight - reconstructed) / np.linalg.norm(weight)
    print(f"[*] 相对重建误差: {error:.6f} (越小越好)")
    
    # 导出
    export_header(A, B, input_dim, output_dim, args.rank, args.output)


if __name__ == "__main__":
    main()